# Generated by Django 5.0.6 on 2024-07-01 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_user_is_verified_user_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='otp_creation_time',
            field=models.DateTimeField(null=True),
        ),
    ]
