# Generated by Django 5.0.6 on 2024-07-01 11:14

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_recipe_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(default='uploads/recipe/default/rice.png', upload_to=core.models.recipe_image_file_path),
        ),
    ]
